version: '2'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
  backend:
    build: .
    # image: weslyg/weekendchallenge:latest
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo
    # environment:
    #   - DB_URL=mongodb://mongo
